/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.snake;

import javax.swing.Box;

/**
 *
 * @author alu10191634
 */
public class Game extends javax.swing.JFrame {

    private static ConfigDialog dialog;
    private static OptionsDialog options;
    private static AboutDialog about;
    
    /**
     * Creates new form Gamesnake
     */
    public Game() {
        initComponents();
        setLocationRelativeTo(null);
        dialog = new ConfigDialog(this, true);
        dialog.setInitGamer(board);
        board.setIncrementer(scoreboard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreboard = new com.mycompany.snake.ScoreBoard();
        board = new com.mycompany.snake.Board();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuEdit = new javax.swing.JMenu();
        jItemConfig = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 102));
        setResizable(false);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        getContentPane().add(scoreboard, java.awt.BorderLayout.PAGE_END);

        board.setPreferredSize(new java.awt.Dimension(900, 900));
        board.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                boardFocusGained(evt);
            }
        });

        javax.swing.GroupLayout boardLayout = new javax.swing.GroupLayout(board);
        board.setLayout(boardLayout);
        boardLayout.setHorizontalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        boardLayout.setVerticalGroup(
            boardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        getContentPane().add(board, java.awt.BorderLayout.LINE_START);

        jMenuBar1.setFocusCycleRoot(true);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenuEdit.setText("Edit");
        jMenuEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jMenuEditFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jMenuEditFocusLost(evt);
            }
        });
        jMenuEdit.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
                jMenuEditMenuDeselected(evt);
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuEditMenuSelected(evt);
            }
        });
        jMenuEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEditMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuEditMousePressed(evt);
            }
        });
        jMenuEdit.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jMenuEditComponentHidden(evt);
            }
        });

        jItemConfig.setText("Configuration");
        jItemConfig.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jItemConfigMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jItemConfig.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jItemConfigFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jItemConfigFocusLost(evt);
            }
        });
        jItemConfig.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jItemConfigComponentHidden(evt);
            }
        });
        jItemConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemConfigActionPerformed(evt);
            }
        });
        jMenuEdit.add(jItemConfig);

        jMenuBar1.add(jMenuEdit);

        jMenuAbout.setText("About");
        jMenuAbout.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenuAboutMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuAbout.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuAboutMenuSelected(evt);
            }
        });
        jMenuAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuAboutMousePressed(evt);
            }
        });

        jMenuItem1.setText("About Game");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAbout.add(jMenuItem1);

        jMenuBar1.add(jMenuAbout);

        jMenuBar1.add(Box.createHorizontalGlue());
        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jItemConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemConfigActionPerformed
        board.pausedGame();
        options = new OptionsDialog(this, true);
        options.setInitGamer(board);
        options.setVisible(true);
    }//GEN-LAST:event_jItemConfigActionPerformed

    private void jMenuEditFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuEditFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEditFocusGained

    private void jMenuEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEditMouseClicked

    }//GEN-LAST:event_jMenuEditMouseClicked

    private void jMenuEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEditMousePressed
        board.pausedGame();
    }//GEN-LAST:event_jMenuEditMousePressed

    private void jMenuEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jMenuEditFocusLost

    }//GEN-LAST:event_jMenuEditFocusLost

    private void jMenuEditComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenuEditComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEditComponentHidden

    private void jItemConfigFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jItemConfigFocusLost

    }//GEN-LAST:event_jItemConfigFocusLost

    private void jItemConfigComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jItemConfigComponentHidden

    }//GEN-LAST:event_jItemConfigComponentHidden

    private void boardFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_boardFocusGained
        //board.continueGame();
    }//GEN-LAST:event_boardFocusGained

    private void jMenuAboutMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuAboutMenuKeyPressed

    }//GEN-LAST:event_jMenuAboutMenuKeyPressed

    private void jMenuAboutMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuAboutMenuSelected

    }//GEN-LAST:event_jMenuAboutMenuSelected

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        board.pausedGame();
        about = new AboutDialog(this, true);
        about.setInitGamer(board);
        about.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAboutMousePressed
        board.pausedGame();
    }//GEN-LAST:event_jMenuAboutMousePressed

    private void jMenuEditMenuDeselected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuEditMenuDeselected
        board.continueGame();
    }//GEN-LAST:event_jMenuEditMenuDeselected

    private void jItemConfigFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jItemConfigFocusGained

    }//GEN-LAST:event_jItemConfigFocusGained

    private void jItemConfigMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jItemConfigMenuKeyPressed
         board.pausedGame();
    }//GEN-LAST:event_jItemConfigMenuKeyPressed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

    }//GEN-LAST:event_formFocusLost

    private void jMenuEditMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuEditMenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEditMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.snake.Board board;
    private javax.swing.JMenuItem jItemConfig;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuEdit;
    private javax.swing.JMenuItem jMenuItem1;
    private com.mycompany.snake.ScoreBoard scoreboard;
    // End of variables declaration//GEN-END:variables
}
