/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.snake;


/**
 *
 * @author asier
 */
public class OptionsDialog extends javax.swing.JDialog{
    public InitGamer initGamer;
    /**
     * Creates new form OptionsDialog
     * @param parent
     * @param modal
     */
    public OptionsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        

    }
    
    public void setInitGamer(InitGamer initGamer) {
        this.initGamer = initGamer;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldOptions1 = new javax.swing.JTextField();
        jLabelDifficulty = new javax.swing.JLabel();
        jLabelMapSize = new javax.swing.JLabel();
        jComboBoxBoardSize = new javax.swing.JComboBox<>();
        jComboBoxDifficulty = new javax.swing.JComboBox<>();
        jButtonNewGame = new javax.swing.JButton();
        jLabelWalls = new javax.swing.JLabel();
        jComboBoxWalls = new javax.swing.JComboBox<>();
        jComboBoxObstacles = new javax.swing.JComboBox<>();
        jLabelObstacles = new javax.swing.JLabel();
        jLabelBackgorund = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(255, 255, 255));
        jLabelName.setText("New name");
        jPanel1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        jTextFieldOptions1.setPreferredSize(new java.awt.Dimension(64, 42));
        jTextFieldOptions1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldOptions1FocusLost(evt);
            }
        });
        jTextFieldOptions1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOptions1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldOptions1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 90, 20));

        jLabelDifficulty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDifficulty.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDifficulty.setText("Difficulty");
        jPanel1.add(jLabelDifficulty, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabelMapSize.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMapSize.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMapSize.setText("Map Size");
        jPanel1.add(jLabelMapSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        jComboBoxBoardSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Big" }));
        jComboBoxBoardSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBoardSizeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxBoardSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jComboBoxDifficulty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Normal", "Expert" }));
        jComboBoxDifficulty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDifficultyActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxDifficulty, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jButtonNewGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/playagainbutton.png"))); // NOI18N
        jButtonNewGame.setToolTipText("");
        jButtonNewGame.setContentAreaFilled(false);
        jButtonNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewGameActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 140, 50));

        jLabelWalls.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelWalls.setForeground(new java.awt.Color(255, 255, 255));
        jLabelWalls.setText("Walls");
        jPanel1.add(jLabelWalls, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jComboBoxWalls.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        jComboBoxWalls.setToolTipText("");
        jComboBoxWalls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxWallsActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxWalls, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jComboBoxObstacles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Yes" }));
        jComboBoxObstacles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxObstaclesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxObstacles, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, -1, -1));

        jLabelObstacles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelObstacles.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObstacles.setText("Obstacles");
        jPanel1.add(jLabelObstacles, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabelBackgorund.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/optionsdialogbackground.jpg"))); // NOI18N
        jPanel1.add(jLabelBackgorund, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, -1, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTextFieldOptions1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOptions1ActionPerformed

    }//GEN-LAST:event_jTextFieldOptions1ActionPerformed

    private void jComboBoxDifficultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDifficultyActionPerformed
        ConfigData.instance.setLevel(jComboBoxDifficulty.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxDifficultyActionPerformed

    private void jButtonNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewGameActionPerformed
        dispose();
        initGamer.initGame();
    }//GEN-LAST:event_jButtonNewGameActionPerformed

    private void jTextFieldOptions1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldOptions1FocusLost
        if (jTextFieldOptions1 != null) {    
            ConfigData.instance.setName(jTextFieldOptions1.getText());
        }
    }//GEN-LAST:event_jTextFieldOptions1FocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        initGamer.continueGame();
    }//GEN-LAST:event_formWindowClosed

    private void jComboBoxBoardSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBoardSizeActionPerformed
        ConfigData.instance.setBoardSize(jComboBoxBoardSize.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxBoardSizeActionPerformed

    private void jComboBoxWallsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxWallsActionPerformed
        ConfigData.instance.setWallLevel(jComboBoxWalls.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxWallsActionPerformed

    private void jComboBoxObstaclesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxObstaclesActionPerformed
        ConfigData.instance.setObstaclesLevel(jComboBoxObstacles.getSelectedIndex());
    }//GEN-LAST:event_jComboBoxObstaclesActionPerformed
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionsDialog dialog = new OptionsDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonNewGame;
    private javax.swing.JComboBox<String> jComboBoxBoardSize;
    private javax.swing.JComboBox<String> jComboBoxDifficulty;
    private javax.swing.JComboBox<String> jComboBoxObstacles;
    private javax.swing.JComboBox<String> jComboBoxWalls;
    private javax.swing.JLabel jLabelBackgorund;
    private javax.swing.JLabel jLabelDifficulty;
    private javax.swing.JLabel jLabelMapSize;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelObstacles;
    private javax.swing.JLabel jLabelWalls;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldOptions1;
    // End of variables declaration//GEN-END:variables

}
